[package]
name = "spanner"
version = "0.1.0"
edition = "2021"

[features]
disable = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = "0.12.1"
once_cell = "1.13.0"
thread_local = "1.1.4"
